version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/HungerFoodBackend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "6868:8080"
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=HungerFoodBackend
    ports:
      - "5433:5432"
volumes:
  db_data: